name: WordScramblers
version: '1.2.08-2025'
main: fr.pixeleur.wordscramblers.WordScramblers
api-version: '1.20'
description: Fully customisable word scrambling game plugin where players unscramble words to win custom rewards.
authors: [Pixeleur]
website: https://pixeleur.fr
commands:
  WordRewardRegister:
    description: Registers the item in your hand as the reward item.
    usage: /WordRewardRegister
    permission: wordscramblers.admin